In [17]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [18]:
df = pd.read_csv('houseprice.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [19]:
model = LinearRegression().fit(df[['area']],df.price)

In [20]:
model.coef_

array([135.78767123])

In [21]:
model.intercept_

180616.43835616432

In [22]:
model.predict([[5000]])

C:\Users\khanm\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [23]:
#process 01
import pickle

In [24]:
with open('pickle_model','wb') as f:
    pickle.dump(model,f)

In [25]:
with open('pickle_model','rb') as f:
    pk_m = pickle.load(f)

In [26]:
pk_m.predict([[5000]])

C:\Users\khanm\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [27]:
#process 02
from joblib import dump, load

In [12]:
dump(model,'joblib_model')

['joblib_model']

In [13]:
j_m = load('joblib_model')

In [14]:
j_m.predict([[5000]])

C:\Users\khanm\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [28]:
j_m.predict([[4600]])

C:\Users\khanm\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([805239.7260274])