In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

import numpy as np

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
X = iris.data
Y = iris.target

In [7]:
from sklearn.model_selection import cross_val_score

In [13]:
lo_score = cross_val_score(LogisticRegression(),X,Y)
lo_score

C:\Users\khanm\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [16]:
np.average(lo_score)

0.9733333333333334

In [17]:
svm_score = cross_val_score(SVC(),X,Y)
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [18]:
np.average(svm_score)

0.9666666666666666

In [19]:
tree_score = cross_val_score(tree.DecisionTreeClassifier(),X,Y)
tree_score

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [20]:
np.average(tree_score)

0.9666666666666668

In [23]:
rf_score = cross_val_score(RandomForestClassifier(n_estimators = 30),X,Y)
rf_score

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [24]:
np.average(rf_score)

0.96